dic_itens_completo = {
"01" : 'Serviços de informática e congêneres.',
"02" : 'Serviços de pesquisas e desenvolvimento de qualquer natureza.',
"03" : 'Serviços prestados mediante locação, cessão de direito de uso e congêneres.',
"04" : 'Serviços de saúde, assistência médica e congêneres.',
"05" : 'Serviços de medicina e assistência veterinária e congêneres.',
"06" : 'Serviços de cuidados pessoais, estética, atividades físicas e congêneres.',
"07" : 'Serviços relativos a engenharia, arquitetura, geologia, urbanismo, construção civil, manutenção, limpeza, meio ambiente, saneamento e congêneres.',
"08" : 'Serviços de educação, ensino, orientação pedagógica e educacional, instrução, treinamento e avaliação pessoal de qualquer grau ou natureza.',
"09" : 'Serviços relativos a hospedagem, turismo, viagens e congêneres.',
"10" : 'Serviços de intermediação e congêneres.',
"11" : 'Serviços de guarda, estacionamento, armazenamento, vigilância e congêneres.',
"12" : 'Serviços de diversões, lazer, entretenimento e congêneres.',
"13" : 'Serviços relativos a fonografia, fotografia, cinematografia e reprografia.',
"14" : 'Serviços relativos a bens de terceiros.',
"15" : 'Serviços relacionados ao setor bancário ou financeiro, inclusive aqueles prestados por instituições financeiras autorizadas a funcionar pela União ou por quem de direito.',
"16" : 'Serviços de transporte de natureza municipal.',
"17" : 'Serviços de apoio técnico, administrativo, jurídico, contábil, comercial e congêneres.',
"18" : 'Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos para cobertura de contratos de seguros; prevenção e gerência de riscos seguráveis e congêneres.',
"19" : 'Serviços de distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules ou cupons de apostas, sorteios, prêmios, inclusive os decorrentes de títulos de capitalização e congêneres.',
"20" : 'Serviços portuários, aeroportuários, ferroportuários, de terminais rodoviários, ferroviários e metroviários.',
"21" : 'Serviços de registros públicos, cartorários e notariais.',
"22" : 'Serviços de exploração de rodovia.',
"23" : 'Serviços de programação e comunicação visual, desenho industrial e congêneres.',
"24" : 'Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres.',
"25" : 'Serviços funerários.',
"26" : 'Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive pelos correios e suas agências franqueadas; courrier e congêneres.',
"27" : 'Serviços de assistência social.',
"28" : 'Serviços de avaliação de bens e serviços de qualquer natureza.',
"29" : 'Serviços de biblioteconomia.',
"30" : 'Serviços de biologia, biotecnologia e química.',
"31" : 'Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres.',
"32" : 'Serviços de desenhos técnicos.',
"33" : 'Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres.',
"34" : 'Serviços de investigações particulares, detetives e congêneres.',
"35" : 'Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas.',
"36" : 'Serviços de meteorologia.',
"37" : 'Serviços de artistas, atletas, modelos e manequins.',
"38" : 'Serviços de museologia.',
"39" : 'Serviços de ourivesaria e lapidação.',
"40" : 'Serviços relativos a obras de arte sob encomenda.',
}

